<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

- 책 시즌에 따라 함수들 따로 만들자

In [1]:
import numpy as np

# Sigmoid 계층
class Sigmoid:
    def __init__(self):
        self.params = []  # 시그모이드 계층 자체에는 학습 파라미터 없음
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))
    

# Affine 계층
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b
        return out

In [2]:
# 간단한 2층 신경망 클래스 구현
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        # 가중치 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        # 계층 생성
        self.layers = [Affine(W1, b1),
                      Sigmoid(),
                      Affine(W2, b2)]
        # 쌓은 계층의 파리미터를 모두 한 곳에 담기
        self.params = []
        for layer in self.layers:
            self.params += layer.params
            
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [4]:
# 테스트
x = np.random.randn(10, 2)  # (batch_size, input_size)
network = TwoLayerNet(2, 10, 3)  # (input_size, hidden_size, output_size)
out = network.predict(x)
print('out shape:', out.shape)
print(out)

out shape: (10, 3)
[[-1.4063818   5.08101953  1.46658765]
 [-1.23446144  4.71059865  1.649346  ]
 [-1.54828591  5.63683197  1.75127779]
 [-1.72853295  5.35982042  1.35035028]
 [-1.13852003  4.47938842  1.81740449]
 [-1.20935076  4.30291987  1.61546482]
 [-1.36719687  5.90093879  2.11093628]
 [-1.1207242   3.90764916  2.01831779]
 [-1.41381632  5.5602985   1.8113028 ]
 [-0.88098549  4.8433152   2.04688153]]


In [10]:
# Repeat 노드
D, N = 8, 7
x = np.random.randn(1, D)
y = np.repeat(x, N, axis=0) # 행 방향으로 복제!
print('x:', x.shape)
print('y:', y.shape)

dy = np.random.randn(N, D) # (7, 8)
dx = np.sum(dy, axis=0, keepdims=True) # 2차원 유지
print('dy:', dy.shape)
print('dx:', dx.shape)

print()
print()

# Sum 노드 - repeat노드와 반대 관계!
D, N = 8, 7
x = np.random.randn(N, D) # (7, 8)
y = np.sum(x, axis=0, keepdims=True)
print('x:', x.shape)
print('y:', y.shape)

# 역전파
dx = np.random.randn(1, D)
dy = np.repeat(dx, N, axis=0)
print('dx:', dx.shape)
print('dy:', dy.shape)

x: (1, 8)
y: (7, 8)
dy: (7, 8)
dx: (1, 8)


x: (7, 8)
y: (1, 8)
dx: (1, 8)
dy: (7, 8)
